const $=s=>document.querySelector(s); const $$=s=>document.querySelectorAll(s);
const money=n=>new Intl.NumberFormat('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' LDS';
function openModal(id){$(id).classList.remove('hidden')} function closeModal(el){el.closest('.modal').classList.add('hidden')}
$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b)); $$('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)m.classList.add('hidden')}));
function findStudent(raw){let c=(raw||'').trim().toUpperCase(); const match=c.match(/LDS[-_ ]?EST[-_ ]?(\d{1,3})/); if(match)c=`LDS-EST-${match[1].padStart(3,'0')}`; return STUDENTS.find(s=>s.codigo===c)}
function showStudent(s){ if(!s){alert('No se encontró ese estudiante.');return;} $('#profileContent').innerHTML=`<div class="profile-head"><div class="avatar">${s.foto?`<img src="assets/${s.foto}" onerror="this.style.display='none'">`:''}</div><div><span class="badge">${s.codigo}</span><h2>${s.nombres||'Estudiante'} ${s.apellidos||''}</h2><p>${s.grado||'Sin grado'} · ${s.seccion||'Sin sección'}</p></div></div><div class="balance"><small>Saldo disponible</small><strong>${money(s.saldo)}</strong></div><div class="grid"><div><span>Sueldo base</span><b>${money(s.sueldo)}</b></div><div><span>Ingresos adicionales</span><b>${money(s.ingresos)}</b></div><div><span>Bonificaciones</span><b>${money(s.bonificaciones)}</b></div><div><span>Egresos</span><b>${money(s.egresos)}</b></div><div><span>Ahorro</span><b>${money(s.ahorro)}</b></div><div><span>Consecuencias</span><b>${money(s.consecuencias)}</b></div></div><button class="primary" onclick="alert('Módulo de movimientos: lo conectaremos a Google Sheets en la siguiente fase.')">Ver movimientos</button>`; openModal('#profileModal') }
$('#scanBtn').onclick=async()=>{openModal('#scannerModal');$('#scanStatus').textContent='Solicitando cámara…'; if(!window.Html5Qrcode){$('#scanStatus').textContent='Cargando lector QR…';setTimeout(()=>startScanner(),500)}else startScanner()};
let scanner; async function startScanner(){if(scanner)return; scanner=new Html5Qrcode('reader'); try{await scanner.start({facingMode:'environment'},{fps:10,qrbox:{width:250,height:250}},async text=>{await scanner.stop();scanner=null;$('#scannerModal').classList.add('hidden');showStudent(findStudent(text));},()=>{});$('#scanStatus').textContent='Cámara activa. Enfoca el código QR.'}catch(e){$('#scanStatus').textContent='No se pudo abrir la cámara. Usa “Ingresar código” o revisa los permisos.';console.error(e)}}
$('#codeBtn').onclick=()=>openModal('#codeModal'); $('#findCode').onclick=()=>showStudent(findStudent($('#codeInput').value)); $('#codeInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#findCode').click()});
$('#adminBtn').onclick=()=>openModal('#adminModal'); $('#adminLogin').onclick=()=>{if($('#pinInput').value===CONFIG.PIN_ADMIN){$('#adminModal').classList.add('hidden');alert('Acceso de administrador correcto. El panel administrativo lo construiremos en la siguiente fase.')}else $('#adminStatus').textContent='PIN incorrecto.'};
